### ISSUE TITLE
Support for sessions?

### ISSUE THREAD

**Issue by henninghorn** [wire-elements/wire-extender#27]
Hi @PhiloNL 

Loving this package! I'm using it together with Filament, which creates a lot for awesome possibilities 🙌 

I'm tickering with sessions together Livewire.
However, I'm not sure if wire-extender supports sessions or I'm simply doing something wrong.

I've tried creating a simple counter component, which stores the count value using the Livewire session attribute. As a full page Livewire Volt component it restore the count value from cache, but when using it as an embedded component, it doesn't seem to be able to restore the value from session.

Got any pointers in this regard? :)

**Comment by JGlueck-WIKA** [comment]
I believe the main problem is, that wire-extender won't apply the "web" middleware which would initialize the session (in `vendor\wire-elements\wire-extender\routes\api.php`).

I just tried to add the following code to my own routing file:

```php
use WireElements\WireExtender\Http\Controllers\EmbedController;

Route::any('livewire/embed', EmbedController::class)->middleware('web');
```

Having that in place, it seems to work retrieving session data, at least on the same domain. When you work cross-domain, you probably also need to make sure that the session cookie is working.

**Comment by JGlueck-WIKA** [comment]
As we have a similar requirement in the near future, I was playing around with this a bit for a cross-domain scenario.

I modified Laravel's `cors.php` so that it looks like this:

```php
<?php

return [

    'paths' => ['livewire/*'],
    'allowed_methods' => ['POST'],
    'allowed_origins' => explode('https://targetdomain.test'),
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true,

];
```

Also changed the value of the `SESSION_COOKIE` environment variable to have a unique name, set `SESSION_SECURE_COOKIE` to `true` and `SESSION_HTTP_ONLY` to false.

When I tested it with these settings, the responses from Wire-Extender contained a header with the session cookie. However, the browser didn't store it. I found out, that I have to change the following wire-extender.js section...

```js
    fetch(getEmbedUri(), {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            components: components
        })
    })
```

... so that it looks like so:

```js
    fetch(getEmbedUri(), {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify({
            components: components
        }),
       'credentials': 'include'
    })
```

Now, the browser will save the session cookie on the target site.

However, it will **not** send it in the request headers on subsequent requests to Wire-Extender, so Laravel cannot continue the session. I must be missing something at this point. @PhiloNL, do you have a tipp? I think it would be very beneficial if we could get the package to support sessions. 🙂

**Comment by PhiloNL** [comment]
@JGlueck-WIKA I think the `credentials` also need to be added here: https://github.com/wire-elements/wire-extender/blob/main/js/wire-extender.js#L73-L75 to ensure this is sent along every Livewire request. If you could give that a try that would be great 😄

**Comment by JGlueck-WIKA** [comment]
@PhiloNL you're a legend! 🔥  That did the trick; got it to work in a local cross-domain scenario.
I've created a PR (#28). Could you please take a look at it when you get a chance? 😀

**Comment by henninghorn** [comment]
@JGlueck-WIKA You're a legend as well! I appreciate you for jumping on this issue and creating a PR so quickly!

**Comment by PhiloNL** [comment]
PR merged 😄  thanks both for the help! Tagged a new release and update the docs.
https://github.com/wire-elements/wire-extender/releases/tag/v0.0.8
