### ISSUE TITLE
Embed Component in Websites Already Using Livewire/Alpine

### ISSUE THREAD

**Issue by mrfelipemartins** [wire-elements/wire-extender#30]
Hi! I am trying to embed a Livewire component in a website that is already using Livewire/Alpine, and I’m encountering the following errors in the browser console:

```
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'onload')
    at waitForLivewireAndStart (wire-extender.js:64:27)
    at wire-extender.js:103:13
```

```
livewire.esm.js:4999 Uncaught (in promise) TypeError: Cannot redefine property: $persist
    at Function.defineProperty (<anonymous>)
    at src_default (livewire.esm.js:4999:14)
    at livewire.esm.js:2766:32
    at Array.forEach (<anonymous>)
    at Object.plugin (livewire.esm.js:2766:17)
    at Object.start (livewire.esm.js:9537:28)
    at startLivewire (wire-extender.js:78:14)
```

I am wondering if it is possible to embed a Livewire component in a website that already uses Livewire, or if this setup creates conflicts.

Thank you!

**Comment by PhiloNL** [comment]
Could you try deferring the script (add defer to the script tag) and see if that works? :) 

```

<script src="https://unpkg.com/@wire-elements/wire-extender" data-uri="https://wire-elements.dev" defer></script>
```

**Comment by PhiloNL** [comment]
> Would it make sense to rename the embeddable tag somehow?
> 
> 
> 
> <livewire
> 
> to
> 
> <wireextender

Not sure, why not use livewire?

**Comment by PhiloNL** [comment]
If `defer` didn't work let me know and I'll re-open the issue.

**Comment by ahosker** [comment]
> Not sure, why not use livewire?

I presume, if I'm using `<livewire` then it gets confused as to which to use, the livewire on the HOST or the EXTENDER livewire.

> If defer didn't work let me know and I'll re-open the issue.

It's not working for me.

If I use Laravel to route to a blade file (without any layout) or an HTML file in public, it works fine.

If I use Laravel to route to a blade file, with livewire in the layout, it does not work.

If I use Laravel to route to a **Full Page Livewire component**, it does not work. 

By "it does not work". I mean it renders the HTML Form but the input values are blank. It also sends livewire requests to the HOST instead of the EXTENDER.

**Comment by PhiloNL** [comment]
I did some digging and I don't think running wire extender within an existing Livewire project will and can work. There is only one Livewire object so this is going to cause problems with Wire Extender because it attempts to initialize Livewire as well with a different updater URL.

**Comment by ahosker** [comment]
The JS code is well above my head, but can we initialize Livewire with a different name so it does not conflict?

**Comment by PhiloNL** [comment]
> The JS code is well above my head, but can we initialize Livewire with a different name so it does not conflict?

I don't think so, that would likely still lead to conflicts; fore example, let's say an embeddable component references the global `Livewire` object instead of the new alias, which would break things as well. I also think all event listeners etc. will be registered twice. So getting this to work would be a significant challenge I think.
